baseurl = "https://example.org/"
languageCode = "en-us"
theme = "hugo-freelancer-theme"
title = "Hugo Freelancer Theme"
[params]
custom_css = []
custom_js = []
description = "My awesome description"
email = "your@email.com"
name = "Mr. Hugo"
[params.about]
left = "I am a game designer with over five years of experience working on mobile free to play and serious games. I explore new design avenues not just in terms of game mechanics but also as Products, UX or solving real world problems."
right = "I have experience working on various aspects of Games or Products including but not limited to: Game Mechanics & Documentation, Balance, Creative Writing, Storyboarding, UI Wireframes & Mock Ups and Market Research."
title = "About"
[params.about.button]
icon = "file"
link = "//docs.google.com/document/d/1wUgsJlBL3qgPONrunk9OViTCu7vI8KDKsAZJsAR2lZM/edit?usp=sharing"
text = "Check out my CV"
[params.contact]
title = "Contact"
[params.contact.form.button]
text = "Send"
[params.contact.form.email]
error = "Please enter your email address."
text = "Email Address"
[params.contact.form.message]
error = "Please enter a message."
text = "Message"
[params.contact.form.name]
error = "Please enter your name."
text = "Name"
[params.contact.form.phone]
error = "Please enter your phone number."
text = "Phone Number"
[params.footer]
copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."
[params.footer.credits]
text = "You can view my other personal projects on [itch.io](//varunraj.itch.io/)."
title = "Personal Projects"
[params.footer.location]
address = ["Hyderabad, India"]
title = "Location"
[params.footer.social]
title = "Around the web"
[[params.footer.social.networks]]
icon = "fa-linkedin"
link = "//linkedin.com/in/varunkoppula/"
[[params.footer.social.networks]]
icon = "fa-behance"
link = "//www.behance.net/kvarunraj"
[params.header]
image = "profile.png"
name = "Varun Raj Koppula"
subtitle = "Game Designer ● UI/UX Designer ● Product Designer & Manager ● Creative Writer & Storyboarder"
[params.navigation]
brand = "Varun On Air"
[params.portfolio]
title = "Portfolio"
[params.portfolio.modal]
buttontext = "Close"
category = "Role"
client = "Company"
date = "Date"
