[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.147.1"
NODE_VERSION = "22"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"